#!/bin/bash

jupyter contrib nbextension install --user
jupyter nbextension enable --py widgetsnbextension
jupyter nbextension enable python-markdown/main
jupyter nbextension enable rubberband/main
jupyter nbextension enable freeze/main
jupyter nbextension enable exercise2/main
jupyter nbextension enable collapsible_headings/main
jupyter nbextension enable autoscroll/main
jupyter nbextension enable init_cell/main
jupyter nbextension enable toggle_all_line_numbers/main
jupyter nbextension enable runtools/main
jupyter nbextension enable splitcell/splitcell
jupyter nbextension enable highlighter/highlighter
jupyter nbextension     enable --py --sys-prefix appmode
jupyter serverextension enable --py --sys-prefix appmode
jupyter nbextension enable --py --sys-prefix ipyvuetify
jupyter nbextension enable --py --sys-prefix ipyturtle

jupyter bundlerextension enable --py jupyter_docx_bundler --sys-prefix

# Notebooks w/ extensions that auto-run code must be "trusted" to work the first time
jupyter trust environnement.ipynb
jupyter trust new.ipynb
jupyter trust cours_00.ipynb
jupyter trust TD_00_1.ipynb
jupyter trust TD_01_1.ipynb
jupyter trust TD_01_1_correct.ipynb
jupyter trust TD_01_2.ipynb
jupyter trust TD_01_2_correct.ipynb
jupyter trust TP_00.ipynb
jupyter trust cours_01_intro.ipynb
jupyter trust cours_01_B.ipynb
jupyter trust cours_01_C.ipynb
jupyter trust cours_01_D.ipynb
jupyter trust cours_01_E.ipynb
jupyter trust cours_01_F.ipynb
jupyter trust TP_codage_des_caracteres_1.ipynb
jupyter trust TP_codage_des_caracteres_2.ipynb
jupyter trust cours_02_intro.ipynb
jupyter trust cours_02_B.ipynb
jupyter trust cours_02_C.ipynb
jupyter trust TD_02_1.ipynb
jupyter trust TD_02_1_correct.ipynb
jupyter trust TD_02_2.ipynb
#jupyter trust TD_02_2_correct.ipynb
